import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/layout/theme-provider"
import { MobileLayout } from "@/components/mobile/mobile-layout"
import { Navbar } from "@/components/layout/navbar"
import { PageTransition } from "@/components/common/page-transition"
import { AppProvider } from "@/contexts/app-context"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <AppProvider>
            <div className="hidden md:block">
              <Navbar />
            </div>
            <div className="md:pt-[90px]">
              <MobileLayout>
                <PageTransition>
                  {children}
                </PageTransition>
              </MobileLayout>
            </div>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
