import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider"
import { MobileLayout } from "@/components/mobile/mobile-layout"
import { Navbar } from "@/components/navbar"
import { ModeToggle } from "@/components/mode-toggle"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <div className="hidden md:block fixed top-0 left-0 right-0 z-50">
            <Navbar />
            <div className="absolute top-8 right-8 z-50">
              <ModeToggle />
            </div>
          </div>
          <div className="md:pt-20">
            <MobileLayout>
              {children}
            </MobileLayout>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
